name: Matrix Demo
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Accounts
        run: |
          echo "Accounts: $ACCOUNT_ALL"
  #deploy:
  #  uses: ./.github/workflows/reusable.yml
  #  with:
  #    accounts: $ACCOUNT_ALL
  #    environment: main