name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        accounts: [12, 14, 16]
        regions: [us-east-1, us-east-2]
    runs-on: ubuntu-latest
    steps:
      - name: Get Accounts
        run: |
          echo "Accounts: {{ matrix.accounts }}"
      - name: Get Regions
        run: |
          echo "Regions: {{ matrix.regions }}"