name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      accounts:
        required: true
        type: string
      regions:
        required: true
        type: string
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        accounts: ["${{ inputs.accounts }}"]
        regions: ${{ fromJson(inputs.regions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Accounts
        run: |
          echo "Accounts: ${{ matrix.accounts }}"
      - name: Get Regions
        run: |
          echo "Regions: ${{ matrix.regions }}"